export const itemsData = [
  {
    itemNumber: 1,
    itemName: "Coffee Black",
    chineseName: "咖啡黑",
    imageURL: "/src/assets/coffee-black.jpg",
    price: 13.5,
    purchased: 44,
    sold: 14,
    inStock: 30,
    purchaseDate: "2025-06-04",
    quantity: 0,
  },
  {
    itemNumber: 2,
    itemName: "Tea Black",
    chineseName: "红茶",
    imageURL: "/src/assets/tea-black.jpg",
    price: 11.3,
    purchased: 91,
    sold: 27,
    inStock: 64,
    purchaseDate: "2025-06-03",
    quantity: 0,
  },
  {
    itemNumber: 3,
    itemName: "Daisy Mum Tea",
    chineseName: "菊花茶",
    imageURL: "/src/assets/chrysanthemum-tea.jpg",
    price: 4.5,
    purchased: 27,
    sold: 17,
    inStock: 10,
    purchaseDate: "2025-06-02",
    quantity: 0,
  },
  {
    itemNumber: 4,
    itemName: "Coffee",
    chineseName: "咖啡",
    imageURL: "/src/assets/coffee.jpg",
    price: 16.5,
    purchased: 71,
    sold: 21,
    inStock: 50,
    purchaseDate: "2025-06-01",
    quantity: 0,
  },
  {
    itemNumber: 5,
    itemName: "Tea",
    chineseName: "茶",
    imageURL: "/src/assets/tea.avif",
    price: 14.5,
    purchased: 67,
    sold: 7,
    inStock: 60,
    purchaseDate: "2025-05-30",
    quantity: 0,
  },
  {
    itemNumber: 6,
    itemName: "Chinese Tea",
    chineseName: "中国茶",
    imageURL: "/src/assets/Chinese Tea.jpg",
    price: 12.5,
    purchased: 41,
    sold: 21,
    inStock: 20,
    purchaseDate: "2025-05-28",
    quantity: 0,
  },
  {
    itemNumber: 7,
    itemName: "Iced Coffee Black",
    chineseName: "冰咖啡黑",
    imageURL: "/src/assets/Iced Coffee Black.jpg",
    price: 11.2,
    purchased: 70,
    sold: 57,
    inStock: 13,
    purchaseDate: "2025-05-27",
    quantity: 0,
  },
  {
    itemNumber: 8,
    itemName: "Iced Tea Black",
    chineseName: "冰红茶",
    imageURL: "/src/assets/Iced Tea Black.jpg",
    price: 15.3,
    purchased: 40,
    sold: 17,
    inStock: 23,
    purchaseDate: "2025-05-25",
    quantity: 0,
  },
  {
    itemNumber: 9,
    itemName: "Soya Milk",
    chineseName: "豆奶",
    imageURL: "/src/assets/Soya Milk.jpg",
    price: 16.5,
    purchased: 37,
    sold: 27,
    inStock: 10,
    purchaseDate: "2025-05-24",
    quantity: 0,
  },
  {
    itemNumber: 10,
    itemName: "Iced Coffee",
    chineseName: "冰咖啡",
    imageURL: "/src/assets/Iced Coffee.jpg",
    price: 13.5,
    purchased: 37,
    sold: 27,
    inStock: 10,
    purchaseDate: "2025-05-22",
    quantity: 0,
  },
  {
    itemNumber: 11,
    itemName: "Iced Tea",
    chineseName: "冰茶",
    imageURL: "/src/assets/Iced Tea.jpg",
    price: 11.7,
    purchased: 47,
    sold: 26,
    inStock: 0,
    purchaseDate: "2025-05-20",
    quantity: 0,
  },
  {
    itemNumber: 12,
    itemName: "Grass Jelly",
    chineseName: "仙草",
    imageURL: "/src/assets/Grass Jelly.jpg",
    price: 5.5,
    purchased: 34,
    sold: 22,
    inStock: 12,
    purchaseDate: "2025-05-18",
    quantity: 0,
  },
  {
    itemNumber: 13,
    itemName: "Coffee C",
    chineseName: "咖啡C",
    imageURL: "/src/assets/Coffee C.jpg",
    price: 16.5,
    purchased: 39,
    sold: 27,
    inStock: 0,
    purchaseDate: "2025-05-15",
    quantity: 0,
  },
  {
    itemNumber: 14,
    itemName: "Tea C",
    chineseName: "茶C",
    imageURL: "/src/assets/Tea C.jpg",
    price: 4.7,
    purchased: 41,
    sold: 17,
    inStock: 24,
    purchaseDate: "2025-05-12",
    quantity: 0,
  },
  {
    itemNumber: 15,
    itemName: "Black & White",
    chineseName: "黑白",
    imageURL: "/src/assets/Black & White.jpg",
    price: 7.3,
    purchased: 41,
    sold: 17,
    inStock: 24,
    purchaseDate: "2025-05-10",
    quantity: 0,
  },
  {
    itemNumber: 16,
    itemName: "Milo",
    chineseName: "美禄",
    imageURL: "/src/assets/Milo.jpg",
    price: 11.9,
    purchased: 41,
    sold: 17,
    inStock: 24,
    purchaseDate: "2025-05-08",
    quantity: 0,
  },
  {
    itemNumber: 17,
    itemName: "Iced Milo",
    chineseName: "冰美禄",
    imageURL: "/src/assets/icedmilo.jpg",
    price: 23.1,
    purchased: 41,
    sold: 17,
    inStock: 24,
    purchaseDate: "2025-05-05",
    quantity: 0,
  },
  {
    itemNumber: 18,
    itemName: "Streamed Bun",
    chineseName: "包子",
    imageURL: "/src/assets/Streamed Bun.jpg",
    price: 5.0,
    purchased: 20,
    sold: 10,
    inStock: 10,
    purchaseDate: "2025-06-05",
    quantity: 0,
  },
  {
    itemNumber: 19,
    itemName: "Steamed Timsum",
    chineseName: "蒸点心",
    imageURL: "/src/assets/Steamed Timsum.jpg",
    price: 6.0,
    purchased: 25,
    sold: 12,
    inStock: 13,
    purchaseDate: "2025-06-04",
    quantity: 0,
  },
  {
    itemNumber: 20,
    itemName: "Deep Fry Timsum",
    chineseName: "炸点心",
    imageURL: "/src/assets/Deep Fry Timsum.jpg",
    price: 6.5,
    purchased: 30,
    sold: 15,
    inStock: 15,
    purchaseDate: "2025-06-03",
    quantity: 0,
  },
  {
    itemNumber: 21,
    itemName: "Bake",
    chineseName: "烘焙",
    imageURL: "/src/assets/Bake.jpg",
    price: 4.0,
    purchased: 22,
    sold: 14,
    inStock: 8,
    purchaseDate: "2025-06-02",
    quantity: 0,
  },
  {
    itemNumber: 22,
    itemName: "Noodle Dumplings",
    chineseName: "面/饺子",
    imageURL: "/src/assets/NoodleDumplings.jpg",
    price: 8.5,
    purchased: 35,
    sold: 20,
    inStock: 15,
    purchaseDate: "2025-06-01",
    quantity: 0,
  },
  {
    itemNumber: 23,
    itemName: "Porridge",
    chineseName: "粥",
    imageURL: "/src/assets/Porridge.jpg",
    price: 7.0,
    purchased: 40,
    sold: 25,
    inStock: 15,
    purchaseDate: "2025-05-31",
    quantity: 0,
  },
  {
    itemNumber: 24,
    itemName: "Takeaway (Water)",
    chineseName: "外卖（水）",
    imageURL: "/src/assets/Takeaway (Water).jpg",
    price: 2.0,
    purchased: 100,
    sold: 80,
    inStock: 20,
    purchaseDate: "2025-05-29",
    quantity: 0,
  },
];

export const requestedItemsData = [
  {
    itemName: "Coffee Black",
    quantity: 50,
    expectedDate: "2025-06-04",
  },
];

export const ItemsMenu = [
  {
    english_name: "Iced Milo",
    chinese_name: "",
    imageURL: "/src/assets/icedmilo.jpg",
  },
];
